In [ ]:
!pip install flair

     |████████████████████████████████| 450kB 8.5MB/s 
     |████████████████████████████████| 19.7MB 1.2MB/s 
     |████████████████████████████████| 983kB 49.3MB/s 
     |████████████████████████████████| 71kB 12.0MB/s 
     |████████████████████████████████| 1.1MB 40.0MB/s 
     |████████████████████████████████| 798kB 47.0MB/s 
     |████████████████████████████████| 1.3MB 48.5MB/s 
     |████████████████████████████████| 890kB 44.5MB/s 
     |████████████████████████████████| 2.9MB 47.8MB/s 
  Created wheel for segtok: filename=segtok-1.5.10-cp36-none-any.whl size=25020 sha256=d45aede7a3bf99240da993cb427a3a7e3910b26cd75f4a5ee0328bdc426c4dad
  Stored in directory: /root/.cache/pip/wheels/b4/39/f6/9ca1c5cabde964d728023b5751c3a206a5c8cc40252321fb6b
  Created wheel for langdetect: filename=langdetect-1.0.8-cp36-none-any.whl size=993193 sha256=49666bbd304eed0606ea7fc05428d8661572406d5875becbd0161003a41796b0
  Stored in directory: /root/.cache/pip/wheels/8d/b3/aa/6d99de9f3841d7d3d40a60e

In [ ]:
import numpy as np
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

In [ ]:
# Glove Embeddings example

glove_embedding = WordEmbeddings('glove')

2020-12-15 22:05:00,800 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmpka44n4ov


100%|██████████| 160000128/160000128 [00:10<00:00, 15771281.86B/s]

2020-12-15 22:05:11,444 copying /tmp/tmpka44n4ov to cache at /root/.flair/embeddings/glove.gensim.vectors.npy


2020-12-15 22:05:11,674 removing temp file /tmp/tmpka44n4ov
2020-12-15 22:05:12,515 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmpy06io5_4


100%|██████████| 21494764/21494764 [00:02<00:00, 8906829.13B/s]

2020-12-15 22:05:15,434 copying /tmp/tmpy06io5_4 to cache at /root/.flair/embeddings/glove.gensim


2020-12-15 22:05:15,455 removing temp file /tmp/tmpy06io5_4


In [ ]:
sent1 = Sentence('apple released iphone 12 pro max in 2020 year')

In [ ]:
# converting into glove_embeddings
glove_embedding.embed(sent1)

[Sentence: "apple released iphone 12 pro max in 2020 year"   [− Tokens: 9]]

In [ ]:
# showing the embedding for each and every word in the sentence
for token in sent1:
  print(token)
  print(token.embedding)

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,

In [ ]:
print(sent1[0])
print(sent1[0].embedding) # first word ..all represent 100 dimensional vector

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,

In [ ]:
sent2 = Sentence('an apple a day keeps a doctor away')

In [ ]:
# converting into glove_embeddings
glove_embedding.embed(sent2)

[Sentence: "an apple a day keeps a doctor away"   [− Tokens: 8]]

In [ ]:
for i in sent2:
  print(i)
  print(i.embedding)
  print('\n')

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0

In [ ]:
sent1[0].embedding.shape , sent2[1].embedding.shape

(torch.Size([100]), torch.Size([100]))

In [ ]:
# Glove distance between same word

glove_dst = distance.euclidean(np.array(sent1[0].embedding),
                               np.array(sent2[1].embedding))
print(glove_dst)

0.0


In [32]:
# Bert Embeddings

bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')

In [33]:
bert_embedding.embed(sent1)
for i in sent1:
  print(i)
  print(i.embedding)

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.3401, -0.0510, -0.0091])
Token: 2 released
tensor([-0.0451, -0.7260,  0.6271,  ...,  0.7689,  0.5975,  0.2122])
Token: 3 iphone
tensor([-0.3609, -0.5975,  0.5235,  ...,  0.9507,  0.2802, -0.9523])
Token: 4 12
tensor([ 0.0730,  0.1813,  0.0204,  ...,  1.0470,  0.4467, -0.1351])
Token: 5 pro
tensor([-0.2332,  0.1988, -0.2101,  ...,  2.0522,  0.7840, -0.2634])
Token: 6 max
tensor([0.3356, 0.1247, 0.2099,  ..., 1.5115, 0.1240, 0.2920])
Token: 7 in
tensor([ 0.0857, -0.2220,  0.1657,  ...,  1.5904, -0.2034, -0.2649])
Token: 8 2020
tensor([-0.1241,  0.3447,  0.9852,  ...,  1.2510,  0.8323, -0.1932])
Token: 9 year
tensor([0.4423, 0.4843, 0.3728,  ..., 1.8454, 0.6008, 0.0384])


In [34]:
bert_embedding.embed(sent2)
for i in sent2:
  print(i)
  print(i.embedding)

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624,  ...,  1.3395,  0.8341,  0.1065])
Token: 2 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.7328,  1.1016,  0.1832])
Token: 3 a
tensor([-0.2709,  0.0440, -0.0203,  ...,  1.0097, -0.4214,  0.6264])
Token: 4 day
tensor([-0.3669,  0.4154,  0.1348,  ...,  0.9116,  0.1781,  0.1328])
Token: 5 keeps
tensor([-0.2821,  0.0814,  1.0041,  ...,  0.2517,  0.6048, -0.0812])
Token: 6 a
tensor([-0.2709,  0.0440, -0.0203,  ..., -0.2629,  0.0617,  0.2902])
Token: 7 doctor
tensor([ 0.0432, -0.4753,  0.1581,  ...,  0.7097,  0.2998,  0.4194])
Token: 8 away
tensor([-0.1038, -0.0148,  0.5993,  ...,  0.9531,  0.3693,  0.3149])


In [35]:
sent1[0].embedding # in sentence 1 apple word is at the 0th index

tensor([-0.5985, -0.4632,  0.1300,  ...,  1.3401, -0.0510, -0.0091])

In [38]:
sent2[1].embedding , sent2[1].embedding.shape # in sentence 2 apple word is at 1st index

(tensor([-0.5985, -0.4632,  0.1300,  ...,  1.7328,  1.1016,  0.1832]),
 torch.Size([3172]))

In [39]:
# Calculating the bert distance
bert_dst = distance.euclidean(np.array(sent1[0].embedding),
                               np.array(sent2[1].embedding))
print(bert_dst)

43.12472152709961
